/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ContactDto {
  address?: string;
  email?: string;
  id?: number;
  name?: string;
  phone?: string;
}
