/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserRole } from '../models/user-role';
export interface UserInfoDto {
  email?: string;
  password?: string;
  roles?: Array<UserRole>;
  user_id?: string;
  username?: string;
}
