/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ContactDto } from '../../models/contact-dto';

export interface UpdateContact$Params {
  id: number;
      body: ContactDto
}

export function updateContact(http: HttpClient, rootUrl: string, params: UpdateContact$Params, context?: HttpContext): Observable<StrictHttpResponse<ContactDto>> {
  const rb = new RequestBuilder(rootUrl, updateContact.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ContactDto>;
    })
  );
}

updateContact.PATH = '/api/contacts/{id}';
